
version: 2

models:
  - name: films
    description: "This table contains details about films"
    columns:
      - name: film_id
        description: "Unique identifier for the films"
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film"
        tests:
          - not_null
      - name : release_date
        description: "Date the film was released"
        tests:
          - not_null
      - name : price
        description: "Price to buy ticket"
        tests:
          - not_null
      - name : rating
        description: "The MPAA rating of the film"
        tests:
          - not_null
      - name : user_rating
        description: "Rating that users gave the film"
        tests:
          - not_null

- name: actors
  description: "This table contains details about the actos."
  columns:
      - name : actor_id
        description: "Unique identifier for the table actors"
        tests:
          - not_null
      - name : name
        description: "Name of the actor"
        tests:
          - not_null

- name: film_actors
  description: "This table contains details about the films to actors that starred in them."
  columns:
      - name : film_id
        description: "Identifier for the each film"
        tests:
          - not_null
      - name : actor_id
        description: "Identifier for each actor"
        tests:
          - not_null


- name: film_ratigns
  description: "This  model aggregates to film data and calculates the average rating for each film."
  columns:
      - name : film_id
        description: "Unique Identifier for the each film"
        tests:
          - not_null
      - name : title
        description: "Title of the film"
        tests:
          - not_null
      - name : release_date
        description: "Date the film was released"
        tests:
          - not_null
      - name : price
        description: "Price to buy ticket"
        tests:
          - not_null
      - name : rating
        description: "The MPAA rating of the film"
        tests:
          - not_null
      - name : user_rating
        description: "Rating that users gave the film"
        tests:
          - not_null
      - name : actor_count
        description: "Number of actors in the film"
        tests:
          - not_null        
      - name : avg_actor_rating
        description: "Averafe rating of the films that the actors of this films have acted in "
        tests:
          - not_null


